#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_quad : require

#define A_GPU 1
#define A_GLSL 1
// define SPD_NO_WAVE_OPERATIONS

#include "ffx_a.h"

layout(set = 0, binding = 0) uniform sampler2D srcDepth;
layout(set = 0, binding = 1, r32f) uniform coherent image2D imgDst[12];
layout(std430, set = 0, binding = 2) coherent buffer SpdGlobalAtomicBuffer {
    uint counter;
} spdGlobalAtomic;

layout(push_constant) uniform HiZPushConstants {
    uint mips;
    uint numWorkGroups;
    uvec2 workGroupOffset;
} pc;

shared AF4 spdIntermediate[16][16];
shared AU1 spdCounter;

AF4 SpdLoadSourceImage(ASU2 p, AU1 slice) {
    float d = texelFetch(srcDepth, p, 0).r;
    return AF4(d, 0.0, 0.0, 0.0);
}

AF4 SpdLoad(ASU2 p, AU1 slice) {
    return imageLoad(imgDst[5], p);
}

void SpdStore(ASU2 p, AF4 value, AU1 mip, AU1 slice) {
    imageStore(imgDst[mip], p, value);
}

void SpdIncreaseAtomicCounter(AU1 slice) {
    spdCounter = atomicAdd(spdGlobalAtomic.counter, 1);
}

AU1 SpdGetAtomicCounter() {
    return spdCounter;
}

void SpdResetAtomicCounter(AU1 slice) {
    spdGlobalAtomic.counter = 0;
}

AF4 SpdLoadIntermediate(AU1 x, AU1 y) {
    return spdIntermediate[x][y];
}

void SpdStoreIntermediate(AU1 x, AU1 y, AF4 value) {
    spdIntermediate[x][y] = value;
}

AF4 SpdReduce4(AF4 v0, AF4 v1, AF4 v2, AF4 v3) {
    return max(max(v0, v1), max(v2, v3));
}

#include "ffx_spd.h"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    SpdDownsample(
        AU2(gl_WorkGroupID.xy),
        AU1(gl_LocalInvocationIndex),
        AU1(pc.mips),
        AU1(pc.numWorkGroups),
        AU1(gl_WorkGroupID.z),
        AU2(pc.workGroupOffset)
    );
}
